/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ersa

import io.ktor.client.*
import io.ktor.client.engine.cio.*

class Courrier(val scheme: String = "https", val host: String, val apiKey: String?=null) {
    val client = HttpClient(CIO)
    init {

    }

    private fun handleHttpError(){}

    private fun _request(){}

    public fun request(){}

    private fun _upload(){}

    public fun upload(){}
}
