/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ersa

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Courrier(host = "https://httbin.org")

    }
}
